name: Generate Recipe Page

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Mindful Chef recipe URL'
        required: true
      slug:
        description: 'Output filename (no extension), e.g. "salmon2"'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate HTML
        run: |
          mkdir -p docs
          node scripts/scrapeRecipe.js "${{ inputs.url }}" docs/${{ inputs.slug }}.html

      - name: Commit generated page
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: add recipe ${{ inputs.slug }}"
          file_pattern: docs/${{ inputs.slug }}.html

